### ISSUE TITLE
When performing model distillation, an error is reported

### ISSUE THREAD

**Issue by LeBron-Jian** [rximg/EfficientAD#10]
distillation_training.py", line 100, in global_channel_normalize
    ldist = item['image'].cuda()
IndexError: too many indices for tensor of dimension 4

请检查提交的代码是否OK？，还是我数据集存在问题？  请帮忙指点
ImageNet
    -train
        -n01440764
        -....
    -val
   -test

**Comment by shellxiao** [comment]
>请问解决了吗？我也遇到了同样的问题。

**Comment by LeBron-Jian** [comment]
数据加载问题

**Comment by hurri2000** [comment]
I met the same question, how did you do?
