### ISSUE TITLE
git lfs pull error

### ISSUE THREAD

**Issue by dldldlfma** [rximg/EfficientAD#12]
When I tried git lfs pull, i saw below message.

batch response: This repository is over its data quoa.
Account responsible for LFS bandwidth should purshase more data packs to restore access.
Failed to fetch some objects from 'https://github.com/rximg/EfficientAD.git/info/lfs'

Could i get data using other ways?

Thank you!

**Comment by 17SIM** [comment]
@dldldlfma I found the following link in the closed issue.
https://github.com/rximg/EfficientAD/releases/tag/0.0.1
