### ISSUE TITLE
how to train teacher model on my own datasets?

### ISSUE THREAD

**Issue by kkpssr** [rximg/EfficientAD#14]
should i train teacher model on my own  datasets with anomaly segment mask and train student model and ae model only on normal sample on my dataset

**Comment by rximg** [comment]
Organize your dataset into MVTec AD format; segment masks are not necessary, and you can use fully black images as masks.

**Comment by watertianyi** [comment]
@rximg 
if i want The training input data is four channels, because my six-channel data is spliced ​​from six single-channel 2D images. How should I modify the code? I do not have a mask annotation file. Can I use this code?
