### ISSUE TITLE
there is an error happen when i get the pretrained weights through "git lfs pull" like this

### ISSUE THREAD

**Issue by MedivhXZ** [rximg/EfficientAD#6]
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/rximg/EfficientAD.git/info/lfs'

**Comment by rximg** [comment]
I have uploaded pretrain weight to the release page, you can get it from there. https://github.com/rximg/EfficientAD/releases/download/0.0.1/EfficientAD_pretrained.zip
