### ISSUE TITLE
Inference on MVtec and ViSa using pretrained weigths

### ISSUE THREAD

**Issue by Ehteshamciitwah** [rximg/EfficientAD#8]
Hello, Thank you for your work. I downloaded the pre-trained weight from the provided link. https://github.com/rximg/EfficientAD/releases/tag/0.0.1

The link contains the weights of only the teacher network. But from where I can get pre-trained weight for the student and autoencoder network? Thank you

**Comment by rximg** [comment]
As long as there is a pre-trained model, any network can be trained, so there is no need to upload other models.
