### ISSUE TITLE
Asking about deployment of onnx format models

### ISSUE THREAD

**Issue by Kyle-fang** [rximg/EfficientAD#9]
Please ask! What is the final output obtained by converting the trained model into onnx format and importing it into onxxruntime for inference? Is it the input sample detection result (and whether it is an anomalous sample) and the corresponding confidence level? Or is it the anomaly_map with the same channel 1 as the input height and width?

**Comment by rximg** [comment]
The output of inference model in eval.py is [”combined_map,image_score“](https://github.com/rximg/EfficientAD/blob/f92e791fe578389630ef8f0cac175c3b496529a7/eval.py#L110C16-L110C40)，combined_map is anomaly_map, image_score is image level anomaly score.
